### PR TITLE
Explain this fork in README

### PR DESCRIPTION
**Pull request by kili-ilo**
This will redirect curious Roc newcomers back to the core repo.

### CODE REVIEW

**Comment by kili-ilo** [comment]
This explanation comes from [this conversation](https://roc.zulipchat.com/#narrow/stream/231635-compiler-development/topic/rustyline.20forks/near/298303563).

**Comment by JanCVanB** [comment]
The goal of this PR is simply to clarify this repo's purpose to visitors, especially those looking to learn more about Roc (like myself) but who are confused (also like myself) as to why this repo is so seemingly-divergent from its upstreams. It's not actually, but I needed to ask for help to figure that out :)

**Comment by kili-ilo** [comment]
@ayazhafiz, could you please review this PR for accuracy?

**Comment by kili-ilo** [comment]
Closing for staleness

**Pull request closed without merging**
